/**
 * Rule: Sparkle / Wand / AI Gimmick Tell (Zero Tolerance)
 * Flags any Sparkles, Wand2, Bot, Cpu, magic-wand, four-point star icon used as decoration;
 * any badge or pill reading "AI", "Generated", "Powered by", "Beta AI", "Smart";
 * or gradient glows purely for AI shimmer.
 */
export function checkSparkles(element) {
  const violations = [];
  const text = (element.innerText || element.textContent || '').trim();
  const className = element.className || '';
  const iconName = element.iconName || '';

  // 1. Icon component inspection
  const aiIcons = ['sparkle', 'sparkles', 'wand', 'wand2', 'bot', 'robot', 'cpu', 'magic'];
  if (aiIcons.some(ai => iconName.toLowerCase().includes(ai) || className.toLowerCase().includes(ai))) {
    violations.push({
      rule: 'Sparkle/wand tell (zero tolerance)',
      element: element.selector,
      iconName: iconName,
      className: className,
      message: `Decorative AI icon component "${iconName || className}" detected.`,
      fix: 'Remove decorative AI icon or replace with domain-specific utility icon (e.g. Receipt, Package, Barcode).'
    });
  }

  // 2. AI Badge / Pill text inspection
  const aiBadgePatterns = /\b(?:AI|Generated by AI|Powered by AI|Beta AI|Smart AI|Magic AI)\b/i;
  if (aiBadgePatterns.test(text) && text.length < 30) {
    violations.push({
      rule: 'Sparkle/wand tell (zero tolerance)',
      element: element.selector,
      sampleText: text,
      message: `AI decoration badge/pill text "${text}" detected in UI.`,
      fix: 'Remove decorative AI badge or replace with clear functional status label.'
    });
  }

  return violations;
}

export default { check: checkSparkles };
